### ISSUE TITLE
Reset PvP combat timer when switching to GM1/Flight

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#131] opened 2018-06-25 06:51 UTC
We got a report of a server operator who apparently had been in active combat mode and then switched to GM1. He reported his FT and tp commands were blocked as the PvP combat timer hadn't reset due to the Mode switch. He and colleagues tested and verified the findings. This appears to be a bug that needs fixed a v.1.1 bugfix version.

**Comment by CraftedMods** [comment] 2018-06-25 09:46
Oh dear. I just found the cause. Will be fixed soon.

**Closed** 2018-06-25 12:37 UTC
Labels: bug, high priority
